variables:

install-and-remove:
  parallel:
    matrix:
      - OCAML_VERSION: "4.10"
        RUST_VERSION:
          - "1.44.0"
          - "1.45.0"
          - "1.46.0"
          - "1.47.0"
          - "1.48.0"
          - "1.49.0"
          - "1.50.0"
          - stable
  image: ocaml/opam2:${OCAML_VERSION}
  before_script:
    - sudo apt-get update
    - sudo apt-get install m4 -y
    - eval $(opam env)
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain ${RUST_VERSION}
    - . $HOME/.cargo/env
    - opam --version
    - ocaml --version
    - cargo --version
    - rustc --version
  script:
    - opam pin --no-action tezos-rust-libs .
    - opam depext tezos-rust-libs
    - opam install --deps-only tezos-rust-libs
    - opam install -v tezos-rust-libs
    - opam remove -a -y tezos-rust-libs
