[workspace]
members = [
    # repository: https://github.com/zcash/zcash
    # revision: c7b2fc101dacfb89f30f911852af7dfb1bf952f2
    # plus small tweaks to Cargo.toml
    "librustzcash",
    # repository: https://github.com/wasmerio/wasmer
    # tag: 2.3.0
    "wasmer-2.3.0/lib/c-api"
]
