[workspace]
members = [
    # repository: https://github.com/zcash/zcash
    # revision: c3a91be47927461d25948932e03be3ae2bf79332
    # plus small tweaks to Cargo.toml
    "librustzcash",
    "rustc-bls12-381",
]
